# Generated by Django 3.2.8 on 2021-10-31 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptom', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatment', models.CharField(max_length=500)),
                ('treat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app3.disease')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(default='none', max_length=500)),
                ('symp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app3.symptom')),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('options', models.CharField(default='none', max_length=100)),
                ('opt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='app3.question')),
            ],
        ),
        migrations.AddField(
            model_name='disease',
            name='symp',
            field=models.ManyToManyField(to='app3.Symptom'),
        ),
        migrations.CreateModel(
            name='Diet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diet_to_follow', models.CharField(max_length=500)),
                ('diet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app3.treatment')),
            ],
        ),
    ]
