# Generated by Django 3.2.8 on 2021-10-31 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatment', models.CharField(max_length=500)),
                ('treat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app3.disease')),
            ],
        ),
        migrations.CreateModel(
            name='Diet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diet_to_follow', models.CharField(max_length=500)),
                ('diet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app3.treatment')),
            ],
        ),
    ]
