# Generated by Django 3.2.6 on 2021-09-16 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='opt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='app3.question'),
        ),
    ]
