# Generated by Django 3.2.8 on 2021-11-01 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0002_diet_treatment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diet',
            name='diet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app3.disease'),
        ),
    ]
